server:
  # Server bind address
  address: "${HTTP_BIND_ADDRESS:0.0.0.0}"
  # Server bind port
  port: "${HTTP_BIND_PORT:8080}"
# MQTT server parameters
custom:
  # Enable/disable mqtt transport protocol.
  enabled: "${CUSTOM_ENABLED:true}"
  bind_address: "${CUSTOM_BIND_ADDRESS:0.0.0.0}"
  bind_port: "${CUSTOM_BIND_PORT:1883}"
  timeout: "${CUSTOM_TIMEOUT:10000}"
  netty:
    leak_detector_level: "${NETTY_LEASK_DETECTOR_LVL:DISABLED}"
    boss_group_thread_count: "${NETTY_BOSS_GROUP_THREADS:1}"
    worker_group_thread_count: "${NETTY_WORKER_GROUP_THREADS:12}"
    max_payload_size: "${NETTY_MAX_PAYLOAD_SIZE:65536}"